[package]
name = "libbittorrent"
version = "0.1.0"
authors = ["CrimsonVoid"]

[lib]
name = "libbittorrent"
path = "src/lib.rs"

[features]
bench = []

[dependencies]
time = "*"
hyper = "*"

[target.'cfg(windows)'.dependencies]
shell32-sys="*"
uuid-sys="*"
ole32-sys="*"
winapi="*"
